
var dicCategories ={

'Standard':
[
'Er morsomst',
'Selv tror den er morsomst',
'Har størst kjendisfaktor',
'Er best i senga',
'Har hatt sex med flest 99ere',
'Spruter den mest massive cumshotten',
'Er mest opptatt av utseende',
'Er mest fornøyd med eget utseende',
'Kommer raskest',
' Har størst penis'  ,
'Har finest smil'  ,
'Er mest overlegen'  ,
'Er mest sporty'  ,
'Har hatt sex med flest'  ,
'Har hatt flest orgasmer'  ,
'Er villest',
'Har best kropp'  ,
'Er mest spontan'  ,
'Er mest uskyldig'  ,
'Lager de sykeste lydene i senga'  ,
'Har størst lommebok'  ,
'Har penest antrekk'  ,
'Har penest legger'  ,
'Har finest rumpe'  ,
'Har penest frisyre'  ,
'Har de vakreste øynene'  ,
'Er mest bredskuldra'  ,
'Har de mest spennende brystene '  ,
'Er festens høyeste  '  ,
'Du har et lite øye til  '  ,
'Slipper de verste fisene  '  ,
'Du får vakrest barn med  '  ,
'Er mest skoleflink  '  ,
'Har shavet og er forberedt på alt  '  ,
'Har lengst tånegler  '  ,
'Er den største fylliken  '  ,
'Er den beste til å kysse  '  ,
'Gir best strippeshow  '  ,
'Har spenstig latter  '  ,
'Har lyst å komme i buksa på i kveld  '  ,
'Bli raskest sjalu  '  ,
'Ligner mest på en taco  '  ,
'Har hatt sex med flest eldre  '  ,
'Har hatt trekant  '  ,
'Liker å bruke buttplug  '  ,
'Har best musikksmak  '  ,
'Har hatt sex med flest nasjonaliteter  '  ,
'Synger best  '  ,
'Synger verst  '  ,
'Snuser mest  '  ,
'Tar med seg noen hjem i kveld  '  ,
'Får kjæreste i år  '  ,
'Blir gravid først  '  ,
'Spyr i kveld  '  ,
'Slutter på studiet  '  ,
'Blir mest drita i kveld  '  ,
'Blir pappa først  '  ,
'Gifter seg først  '  ,
'Har finest lepper  '  ,
'Har størst fot  '  ,
'Er mest klar for arbeidslivet  '  ,
'Kler briller best  '  ,
'Skiller seg mest ut i mengden  '  ,
'Ligner mest på en høne  '  ,
'Rir best  '  ,
'Stikker mest  '  ,
'Lukter best  '  ,
'Lyser opp rommet  '  ,
'Runker mest  '  ,
'Tar seg mest på brystene  '  ,
'Ser mest på porno  '  ,
'Fingrer mest  '  ,
'Drikker raskest  '  ,
'Googler seg selv oftest  '  ,
'Gir mest til veldedighet  '  ,
'Spiller et instrument best  '  ,
'Er en svett gamer  '  ,
'Er mest fotogen  '  ,
'Har blitt pumpa  '  ,
'Er den verste sjåføren  '  ,
'Mest religiøs  '  ,
'Har hatt sex i et telt  '  ,
'Du ville vært på en øde øy med  '  ,
'Har flest filmer på telefonen sin  '  ,
'Bruker fake ID  '  ,
'Har hatt sex utendørs  '  ,
'Oftest forsinket  '  ,
'Har korteste telefonsamtaler  '  ,
'Er mest ubesluttsom  '  ,
'Tror på synske  '  ,
'Er minst flink til å bruke prevensjon  '  ,
'Ser på The Kardashians  '  ,
'Er mest bortskjemt  '  ,
'Jukser mest  '  ,
'Har hatt kjønnssykdommer  '  ,
'Har mest humørsvingninger  '  ,
'Har størst baller  '  ,
'Kunne spist mest sushi  '  ,
'Er lengst i dusjen  '  ,
'Skal ta bonski sammen med deg  '  ,
],


'Bli kjent': [
'Hvem har styggest navn?',
'Hvem har høyest utdanning?',
'Hvem er flinkest til å lyve?',
'Hvem er den peneste i rommet?',
'Hvem har hoppet i fallskjerm?',
'Hvem har hoppet i strikk?',
'Hvem har mestret et instrument?',
'Hvem er den mest kreative?',
'Hvem har den bredeste dialekten?',
'Hvem er mest bereist?',
'Hvem er flinkest i senga?',
'Hvem elsker å stå på scenen?',
'Hvem har en hemmelig elsker ingen vet om?',
'Hvem kommer garantert til å gå hjem alene i kveld?',
'Hvem kommer garantert til å gå hjem sammen med noen i kveld?',
'Hvem kommer til å bli milliardær?',
'Hvem kommer til å havne i fengsel?',
'Hvem kommer til å bli uteligger?',
'Hvem kommer til å få barn først?',
'Hvem er den største alkisen i rommet?',
'Hvem tåler kritikk dårligst?',
'Hvem er den mest jordnære personen i rommet?',
'Hvem har det fineste smilet?',
'Hvem sitter å fiser i all hemmelighet?',
'Hvem ville du helst sittet i karantene med?',
'Hvem ligner mest på Shrek?',
'Hvem bytter sjeldnest truse?',
'Hvem spiser mest Fjordland?',
'Hvem er mest handy?',
'Hvem her er den som hadde tatt seg best ut på reality tv?',
'Hvem tar en utdanning som de faktisk er fornøyd med?',
'Hvem følger faktisk drømmen sin?',
'Hvem kommer til å bli reinkarnert som en slange?',
'Hvem har et hemmelig alterego som superstjerne?',
'Hvem er mest sannsynlig å ende opp på NAV?',
'Hvem er kjedeligst?',
'Hvem er dårligst med penger?'
'Hvem kunne vært med i Ringenes Herre?',
'Hvem blir superskurk?',
'Hvem kommer til å slå barna sine?',
'Hvem ypper på byen?',
"Hvem er bedreviter?",
'Hvem kommer til å starte egen business?',
'Hvem her kommer til å bli narkis?',
'Hvem er mest negativ?',
'Hvem er pushover?',
'Hvem er en naturlig leder?',
'Hvem har den dårligste tinderprofilen?',
'Hvem har mer enn 3 datingapper på telefonen',
"Hvem er mest spandabel?",
"Hvem er mest religiøst?",
"Hvem er grammatisk Nasist?",
"Hvem drikker kun flaskeøl?",
"Hvem er minst glad i Norge?",
"Hvem ville ofret livet sitt for monarkiet?",
"Hvem hadde desertert om det hadde blitt krig?",
"Hvem er kleinest å snakke med?",
"Hvem drar spøker som aldri slår ann?",
"Hvem har mest penger?",
"Hvem har minst alko-blære?",
"Hvem blir alltid igjen å rydder opp etter vors?",
"Hvem drar bare på vors for å finne kjærligheten?",
"Hvem har dårligst smak på interiør?",
"Hvem har dårligst klesstil?",
"Hvem er dum men vet det ikke selv?",
"Hvem velger alkohol over sex?",
"Hvem er mest rotete?",
"Hvem gjør aldri noe nytt?",
"Hvem sier de er singel, men er egentlig ikke det?",
"Hvem har den kjipeste eksen?",
"Hvem lar ikke regler stoppe seg?",
"Hvem er en glider?",
"Hvem tar alltid bilde i speilet på gymmen?",
"Hvem blir alltid for drita?",
"Hvem er limet til vorset?",
"Hvem hadde du ikke merket at hadde manglet på vorset?",
"Hvem har den rareste avhengigheten?",
"Hvem her kunne vært en seriemorder og ingen hadde visst det?",
"Hvem er korps-kid?",
"Hvem var den styggeste babyen?",
"Hvem er adrenalinjunkie?",
"Hvem er øl-entusiast?",
"Hvem blir stoppet av politiet i fartskontroll?",
"Hvem er kontrollfreak",
"Hvem er minst kresen",
"Hvem har dårligst manerer?",
"Hvem er dårligst i engelsk?",
"Hvem lager best mat?",
"Hvem er obsessed med penger?",
"Hvem er den lateste personen i rommet?",
"Hvem har flest fiender?",
"Hvem har et hemmelig forhold til Gud?",
"Hvem er en lesehest?",
"Hvem jukser alltid på prøver?",
"Hvem er nerden i rommet?",
"Hvem leker alltid psykolog?",
"Hvem har de rareste vanene?",
"Hvem tar aldri telefonen?",
"Hvem kommer alltid for tidlig?",
"Hvem går i samme klær hver dag?",
"Hvem har høyest IQ?",
"Hvem kunne vært utro?",



],
'Sex' : [
"Hvem er holder lengst i senga?",
"Hvem er jomfru?",
"Hvem har hatt sex med over 50 personer?",
"Hvem sliter alltid med å få stå?",
"Hvem holder kortest i senga?",
"Hvem kunne hatt sex med 100 personer?",
"Hvem har aldri hatt sex edru?",
"Hvem har aldri hatt et one night stand?",
"Hvem bruker aldri kondom?",
"Hvem elsker å ha sex offentlig?",
"Hvem har pult på en do?",
"Hvem har hatt sex med en lærer / lærerassistent?",
"Hvem har hatt sex på jobb?",
"Hvem har slikket noen i anus?",
"Hvem har møtt noen på nettet for anonym sex?",
"Hvem har tissa på partneren sin?",
"Hvem bruker alltid leketøy i senga?",
"Hvem runker mest?",
"Hvem lyver om at de går på p-piller?",
"Hvem kunne du hooket opp med i rommet her?",
"Hvem skal være med på trekanten deres?",
"Hvem fingrer mest?",
"Hvem har mest analsex?",
"Hvem har kjøpt en seksuell tjeneste?",
"Hvem har filmet seg selv under sex?",
"Hvem har gjort en striptease på kamera?",
"Hvem har onanert med en grønnsak?",
"Hvem har hatt sex mens det har vært noen andre til stede i rommet?",
"Hvem liker en finger i stinken under akten?",
"Hvem liker å bli kvalt til de ikke kan puste under akten?",
"Hvem har pult en kjendis?",
"Hvem shaver aldri?",
"Hvem shaver hver gang de skal ut?",
"Hvem tør ikke å snakke med det motsatte kjønn om de ikke er beruset?",
"Hvem av det motsatte kjønn har finest kropp?",
"Hvem i rommet har lengst pikk?",
"Hvem i rommet har en eldgammel kondom i lommeboka?",
"Hvem har hatt sex mest minst?",
"Hvem i rommet har kortest pikk?",
"Hvem i rommet har en fotfetish?",
"Hvem i rommet har ligget med flest?",
"Hvem i rommet har hatt flest orgasmer?",
"Hvem i rommet gir verst strippeshow?",
"Hvem i rommet er en eksibisjonist?",
"Hvem i rommet eier flest sexleketøy?",
"Hvem i rommet har en sexdukke?",
"Hvem i rommet har en sugardaddy?",
"Hvem i rommet skifter personlighet i senga?",
"Hvem i rommet liker å få en golden shower?",
"Hvem i rommet tror de selv er best i senga?",
"Hvem er mest submissive i rommet?",
"Hvem i rommet ville du valgt som den eneste personen du kunne hatt sex med til du dør?",
"Hvem svelger alltid?",
"Hvem har mest sex?",
"Hvem svelger aldri?",
"Hvem er kjedeligst i senga?",
"Hvem i dette rommet kunne du hatt anal med?",
"Hvem i dette rommet ser mest på hentai?",
"Hvem i dette rommet hadde blitt den beste pornostjerna?",
"Hvem er best til å suge pikk?",
"Hvem er best til å slikke mus?",
"Hvem bruker viagra på fylla?",
"Hvem har onanert mens de har fantasert om noen i dette rommet?",
"Hvem i dette rommet tenker du på / kunne du tenkt på mens du onanerte?",
"Hvem i dette rommet kunne du sendt melding til på byen?",
"Hvem i dette rommet er mest desperat etter et ligg?",
"Hvem i rommet takler flest peniser samtidig?",
"Hvem i rommet hadde blitt fryst ut av en trekant?",
"Hvem i rommet har hatt sex for siste gang?",
"Hvem mistet jomfrudommen til et one night stand?",
"Hvem har hatt flest kjønnssykdommer?",
"Hvem har vært i en orgie?",
"Hvem har onanert på skole / jobb?",
"Hvem har med seg noen nye hjem hver helg?",
"Hvem liker å bli spyttet i kjeften?",
"Hvem liker å bli slått i senga?",
"Hvem faker alltid orgasme?",
"Hvem har kun hatt 1 sexpartner?",
"Hvem holder lengst i senga?",
"Hvem i rommet vil du helst se naken?",
'Hvem i rommet vil du helst ikke se naken?',
"Hvem i rommet ville du betalt for å ha med deg hjem?",
"Hvem i rommet ligger alltid på første date?",
"Hvem betaler for porno?",
"Hvem kunne datet en pornostjerne?",
"Hvem ligger kun med folk i vennekretsen?",
"Hvem er mest interessert i BDSM?",
"Hvem har et hemmelig liv som dominatrix?",
"Hvem har alltid bind for øynene under sex?",
"Hvem hadde gjort det best som telefonsexoperatør?",
"Hvem liker å se på andre ha sex?",
"Hvem er swingers?",
"Hvem tenner på lakk og lær?",
"Hvem liker roleplay?",
"Hvem elsker fisting?",
"Hvem tenner på scat porn?",
"Hvem var jomfru lengst / er fremdeles jomfru?",
"Hvem er søppelbøtta i gjengen?",
"Hvem tenner på dyreporno?",
"Hvem hater morgensex?",
"Hvem skriver liste over alle sine sexpartnere?",



],
"Guttavors" : [
"Hvem er svakest?",
"Hvem runker mest?",
"Hvem har blitt catchet av foreldrene sine?",
"Hvem har pult flest damer?",
"Hvem runker mest på skolen?",
"Hvem blir alltid friend-zonet?",
"Hvem har brutt bro-code?",
"Hvem blir avvist mest på byen?",
"Hvem driver 'Tøm og Røm AS'?",
"Hvem er mest feminin?",
"Hvem har best drag på jenter?",
"Hvem er mest maskulin?",
"Hvem har ligget med den yngste?",
"Hvem har ligget med den eldste?",
"Hvem er mest kresen?",
"Hvem hadde ikke klart å tilfredsstille to jenter på en gang?",
"Hvem blir gift først?",
"Hvem har størst baller?",
"Hvem har tinder gold?",
"Hvem blir først far?",
"Hvem har den mest hårete bakdelen?",
"Hvem har møtt flest fra tinder?",
"Hvem har gått på flest smeller?",
"Hvem gjør alltid den dummeste dritten på fylla?",
"Hvem har størst sjanse for å vippe ut kuken i løpet av vorset?",
"Hvem er den sterkeste i rommet?",
"Hvem sender dama på dør først?",
"Hvem er den største romantikeren i rommet?",
"Hvem i rommet er hemmelig i skapet?",
"Hvem i rommet er best i beerpong?",
"Hvem i rommet har dårligst draget på damene?",
"Hvem i rommet tisser i senga?",
"Hvem i rommet er allergisk mot kondom?",
"Hvem i rommet ryker på hva som helst?",
"Hvem i rommet får mest Whiskeydick?",
"Hvem i rommet har alt for høye standarder?",
"Hvem i rommet kunne ligget med moren til en kompis?",
"Hvem liker biler mer enn damer?",
"Hvem er babyface?",
"Hvem gir ingen inntrykk for at de er interessert i damer?",
"Hvem kommer til å være utro mot kona si?",
"Hvem fyrer hardest på vors?",
"Hvem har best skjegg?",
"Hvem bryr seg mest om utseende?",
"Hvem bruker for mye voks?",
"Hvem tar mest plass i rommet?",
"Hvem er mest introvert?",
"Hvem er han som drar ut gitaren på nach?",
"Hvem ligner mest på Joe Exotic?",
"Hvem er mammadalten i rommet?",
"Hvem har en fæffa som betaler?",
"Hvem later som er noe de ikke er?",
"Hvem hadde blitt kjendis om de prøvde?",
"Om alle i rommet hadde fått sjans til å prøve seg på Megan Fox, hvem hadde vunnet henne?",
"Hvem kunne vært en karakter fra Exit?",
"Hvem er mest harry?",
"Hvem kommer til å gamble bort formuen sin?",
"Hvem hadde sett best ut som drag queen?",
"Hvem kommer til å bo lengst hjemme?",
"Hvem har mest plass til overs når de ruller ut kondomen?",
"Hvem er mest handy?",
"Hvem er mest guttastemning?",
"Hvem er adrenalinjunkie?",
"Hvem kunne sterilisert seg uten å si det til partneren sin?",
"Hvem kunne blitt spermdonor?",
"Hvem har smakt på sitt eget cum?",
"Hvem har lengst pung?",
"Hvem ender alltid i baris?",
"Hvem er mest kreativ i senga?",
"Hvem i rommet ler høyest?",
"Hvem er mest irriterende?",
"Hvem kommer til å sovne med en pizza i hånden?",
"Hvem snorker mest?",
"Hvem tar flest selfies?",
"Hvem kommer seg ikke inn på byen i kveld?",
"Hvem har den mest skitne logg-historien på datamaskinen?",
"Hvem hører på dårligst musikk?",
"Hvem kler ikke briller?",
"Hvem er den svetteste kisen i rommet?",
"Hvem får flest barn med flest damer?",
"Hvem tar alltid en for laget?",
  "Hvem er mest fornøyd med eget utseende?",
  "Hvem kunne ligget med en kjendis, bare fordi personen var kjent?",
  "Hvem er mest keen på kjæreste?",
  "Hvem er mest fornøyd med egen kropp?",
  "Hvem har vært forelsket i læreren sin?",
  "Hvem har størst busk?",
  "Hvem får flest matcher på tinder?",
  "Hvem drar alltid ut på byen med et mål om å kline?",
  "Hvem er mest sannsynlig til å bli med en random hjem fra byen i kveld?",
  "Hvem har commitment issues?",
  "Hvem er høyest på seg selv?",
  "Hvem i rommet får ikke lov til å gi blod?",
  "Hvem er den største psykopaten?",
  "Hvem kunne ligget seg til toppen av karrierestigen?",
  "Hvem kommer til å være ugjenkjennelig om 10 år?",
  "Hvem har sittet å sluppet snikfiser hele spillet?",
  "Hvem kommer til å ta ungen sin i hånda fremfor en klem?",
  "Hvem er den raskeste chuggeren?",
  "Hvem skal du ha chuggekonk med?",

],
"Jentevors":  [
"Hvem ser penest ut i kveld?",
"Hvem har lurt noen til å sengs?",
"Hvem har sympati-hooket noen?",
"Hvem har best drag på gutter?",
"Hvem kunne hatt en sugardaddy?",
"Hvem har ligget med den yngste?",
"Hvem har ligget med den eldste?",
"Hvem er mest fornøyd med eget utseende?",
"Hvem sladrer mest?",
"Hvem kommer til å bli en cougar?",
"Hvem er mest kresen?",
"Hvem gifter seg først?",
"Hvem blir stay at home mom?",
"Hvem blir gravid først?",
"Hvem får flest ektemenn i løpet av livet?",
"Hvem kommer til å flytte til utlandet?",
"Hvem blir alenemor?",
"Hvem har ligget med en kjendis?",
"Hvem blir smelt på tjukka av en random på byen?",
"Hvem kunne ligget med en kjendis, bare fordi personen var kjent?",
"Hvem liker det HARDEST i senga?",
"Hvem er en sjøstjerne i senga?",
"Hvem har størst kjendisfaktor?",
"Hvem er mest keen på kjæreste?",
"Hvem har daddyissues?",
"Hvem er verpesyk?",
"Hvem er mest fornøyd med rumpa si?",
"Hvem har tinder gold?",
"Hvem er mest fornøyd med egen kropp?",
"Hvem er mest sannsynlig å melde seg på et reality-program?",
"Hvem har de fineste puppene?",
"Hvem kommer til å ende opp som kattedame?",
"Hvem kunne vunnet Miss Universe?",
"Hvem har vært forelsket i læreren sin?",
"Hvem bruker for mye sminke?",
"Hvem shotter mest?",
"Hvem i rommet har jungelfeber?",
"Hvem er mest fan av babyface?",
"Hvem i rommet bruker mest penger på klær?",
"Hvem i rommet er en gold digger?",
"Hvem er mest løs?",
"Hvem er villig for til å være singel i 15 år for å gifte seg med prins Sverre Magnus?",
"Hvem prøver for hardt å bli influenser?",
"Hvem synger finest?",
"Hvem har størst busk?",
"Hvem lukter best?",
"Hvem har hatt den kjekkeste kjæresten?",
"Hvem får mest matcher på tinder?",
"Hvem er best på kjøkkenet?",
"Hvem drar alltid ut på byen med et mål om å kline?",
"Hvem får flest barn?",
"Hvem kommer til å bli dårligst mor?",
"Hvem kommer først til å ta botox?",
"Hvem blir skilt flest ganger?",
"Hvem er mest sannsynlig til å bli med en random hjem fra byen i kveld?",
"Hvem kjøper aldri sin egen drikke på byen?",
"Hvem har commitment issues?",
"Hvem er størst luremus?",
"Hvem minner mest om Regina George?",
"Hvem er mest oppmerksomhetssyk?",
"Hvem syns det er mest turn-off med lavere gutter?",
"Hvem sier at de ikke bryr seg om utseende på en gutt mens de egentlig gjør det?",
"Hvem bruker mest push-up?",
"Hvem ser alltid ut som en Oompa Loompa?",
"Hvem var hestejente?",
"Hvem photoshopper bildene sine på instagram?",
"Hvem bryr seg mer om plantene enn vennene sine?",
"Hvem ligner mest på Carole Baskin?",
"Hvem er høyest på seg selv?",
"Hvem er feminazi?",
"Hvem har den styggeste bunaden?",
"Hvem fisker alltid etter komplimenter?",
  "Hvem har gått på flest smeller?",
"Hvem kunne vært i kunne vært en karakter i Keeping Up With The Kardashians?",
"Hvem kunne blitt eggdonor?",
"Hvem svelger alltid?",
"Hvem er mest overtroisk?",
  "Hvem har blitt catchet av foreldrene sine?",
  "Hvem blir alltid friend-zonet?",
  "Hvem blir avvist mest på byen?",
  "Hvem er mest maskulin?",
  "Hvem har møtt flest fra tinder?",
  "Hvem er den største romantikeren i rommet?",
  "Hvem i rommet er best i beerpong?",
  "Hvem i rommet tisser i senga?",
  "Hvem i rommet er allergisk mot kondom?",
  "Hvem i rommet har alt for høye standarder?",
  "Hvem får flest matcher på tinder?",
  "Hvem bryr seg mest om utseende?",
  "Hvem tar mest plass i rommet?",
  "Hvem er mest introvert?",
  "Hvem har en fæffa som betaler?",
  "Hvem later som er noe de ikke er?",
  "Hvem hadde blitt kjendis om de prøvde?",
  "Hvem kunne vært en karakter fra Exit?",
  "Hvem er mest harry?",
  "Hvem er mest handy?",
  "Hvem i rommet får ikke lov til å gi blod?",
  "Hvem er den største psykopaten?",
  "Hvem kunne ligget seg til toppen av karrierestigen?",
],






};


var JenterGutter={
"Hvem har lurt noen til å sengs?"
"Hvem har blitt catchet av foreldrene sine?",
"Hvem er mest fornøyd med eget utseende?",
"Hvem blir alltid friend-zonet?",
"Hvem gifter seg først?",
"Hvem blir avvist mest på byen?",
"Hvem kommer til å flytte til utlandet?",
"Hvem er mest maskulin?",
"Hvem har ligget med den yngste?",
"Hvem har ligget med den eldste?",
"Hvem er mest kresen?",
"Hvem har ligget med en kjendis?"
"Hvem blir gift først?",
"Hvem har tinder gold?",
"Hvem kunne ligget med en kjendis, bare fordi personen var kjent?",
"Hvem har møtt flest fra tinder?",
"Hvem har gått på flest smeller?",
"Hvem gjør alltid den dummeste dritten på fylla?",
"Hvem har størst kjendisfaktor?",
"Hvem er mest keen på kjæreste?",
"Hvem er den største romantikeren i rommet?",
"Hvem har tinder gold?",
"Hvem er mest fornøyd med egen kropp?",
"Hvem er mest sannsynlig å melde seg på et reality-program?",
"Hvem i rommet er best i beerpong?",
"Hvem har vært forelsket i læreren sin?",
"Hvem i rommet tisser i senga?",
"Hvem i rommet er allergisk mot kondom?",
"Hvem shotter mest?",
"Hvem har størst busk?",
"Hvem i rommet har alt for høye standarder?",
"Hvem får flest matcher på tinder?",
"Hvem er best på kjøkkenet?",
"Hvem drar alltid ut på byen med et mål om å kline?",
"Hvem får flest barn?",
"Hvem blir skilt flest ganger?",
"Hvem er mest sannsynlig til å bli med en random hjem fra byen i kveld?",
"Hvem bryr seg mest om utseende?",
"Hvem har commitment issues?",
"Hvem er høyest på seg selv?",
"Hvem tar mest plass i rommet?",
"Hvem er mest introvert?",
"Hvem har en fæffa som betaler?",
"Hvem later som er noe de ikke er?",
"Hvem hadde blitt kjendis om de prøvde?",
"Hvem kunne vært en karakter fra Exit?",
"Hvem er mest harry?",
"Hvem kommer til å bo lengst hjemme?",
"Hvem er mest handy?",
"Hvem kommer aldri til å komme inn på boligmarkedet",
"Hvem i rommet får ikke lov til å gi blod?",
"Hvem er den største psykopaten?",
"Hvem kunne ligget seg til toppen av karrierestigen?",

};



var Challenges ={
"sporsmol":[
"Hvem er den snilleste personen i rommet?",
"Hvem er mest aktiv på tinder?",
"Hvem er mest kreativ i senga?",
"Hvem i rommet inspirerer deg til å bli et bedre menneske?",
"Hvem i rommet har hatt flest sexpartnere?",
"Hvem i rommet er finest på håret?",
"Hvem i rommet har finest klær?",
"Hvem i rommet har finest tenner?",
"Hvem i rommet har du et godt øye til?",
"Hvem i rommet er mest sjenert når det kommer til det motsatte kjønn?",
"Hvem i rommet er mest aktiv på Instagram?",
"Hvem i rommet er sterkest?",
"Hvem i rommet har best kropp?",
"Hvem i rommet har best sjekketriks?",
"Hvem i rommet drikker mest?",
"Hvem i rommet drikker minst?",
"Hvem i rommet skal bli winget i kveld?",
"Hvem i dette rommet har finest sangstemme?",
"Hvem i dette rommet har best hukommelse?",
"Hvem i dette rommet er best på å chugge?",
"Hvem er den ærligste personen i rommet?",
"Hvem har det mest interessante sexlivet?",
"Hvem i rommet tar størst plass'?",
"Hvem er den beste kysseren i rommet?",
"Hvem i rommet har du mest lyst til å kysse?",
"Hvem i rommet er mest hemmelighetsfull?",
"Hvem i rommet er mest åpen seksuelt?",
"Hvem er mest kresen?",
"Hvem er den mest kreative i rommet?",
"Hvem er alltid hemmelighetsfull med hva de gjør på mobilen?",
"Hvem i dette rommet ville du byttet liv med?",
"Hvem i rommet er den største flørteren?",
"Hvem i rommet tror/håper det er snakk om seg?",
"Hvem tar de beste avgjørelsene?",
"Hvem er den beste danseren?",
"Hvem forsvinner først og tar med noen hjem?",
"Hvem er på den lengste tørkeperioden?",
"Hvem har best draget på det motsatte kjønn?",
"Hvem er den diggeste personen i rommet?",
"Hvem her ler mest?",
"Hvem er det største villdyret her?",
"Hvem er den fjerneste personen i rommet?",
"Hvem i rommet har best luktesans?",
"Hvem er mest generøs?",
"Hvem i rommet elsker tatoveringer?",
"Hvem er flinkest til å ta bilder?",
"Hvem gir verst striptease?",
"Hvem tar de minste slurkene?",
"Hvem er den største løken i rommet?",
"Hvem i rommet er mest glad i oralsex?",
"Hvem er den mest sosiale i rommet?",
"Hvem elsker bursdager?",
"Hvem bruker snapchat mest?",
"Hvem er den beste skuespilleren i rommet?",
"Hvem er den mest kosete personen i rommet?",
"Hvem er dårligst på dialekter?",
"Hvem er mest komfortabel med sin egen kropp?",
"Hvem i rommet maler et bilde med ord? Altså, den mest kreative taleren",
"Hvem er den mest spontane personen i rommet?",
"Hvem er den beste selgeren i rommet?",
"Hvem her har brukt en banan for å tilfredsstille seg selv?",
"Hvem er den mest sensuelle personen i rommet?",
"Hvem sier alltid hva de mener?",
"Hvem liker best å se seg selv i speilet?",
"Hvem syns du er søtest i rommet?",
"Hvem gjør de sykeste tingene i senga?",
"Hvem har best balanse?",
"Hvem trenger hjelp i datinglivet sitt?",
"Hvem kommer til å gifte seg først?",
"Hvem er den største partyløven?",
"Hvem er den største playeren i rommet?",
"Hvem her hadde du absolutt ikke angret på å hooke opp med dagen etter?",
"Hvem i rommet tror de selv er best i senga?",
"Hvem i rommet er faktisk best i senga?",
"Hvem i rommet kunne vært med på Paradise Hotel?",
"Hvem i rommet tror du chugger fortest?",
"Hvem er den beste dirty talkeren?",
"Hvem er mest fornøyd med pikken sin?",
"Hvem er minst sjefete?",
"Hvem har tørrest lepper?",
"Hvem banner mest?",
"Hvem i rommet er evig singel?",
  "Hvem i rommet blir gravid først?",
  "Hvem har dårligst musikksmak?",
  "Hvem snylter på andres alkohol?",
  "Hvem trenger en hårklipp?",
  "Hvilken person at det motsatte kjønn hadde sett best ut i dine klær?",
  "Hvem sier ja til alt?",
  "Hvem i rommet er mest handy?",
  "Hvem ser ut som de har på seg minst klær?",
  "Hvem er den største adrenalin junkien?",
  "Hvem er mest alternativ?",
  "Hvem er stuck på 90-tallet?",
  "Hvem må drikke mer?",
  "Hvem burde vært med på Skal Vi Danse?",
  "Hvem i rommet tror du at du hadde slått i en push-up konkurranse?",
  "Hvem er den største komikeren?",
  "Hvem bryr seg ikke om klima og miljø?",
  "Hvem er mest omtektsom?",
  "Hvem er mest feminin?",
  "Hvem har styggest navn?",
  "Hvem er mest sannsynelig å have i fengsel?",

],
"svar":[
"Siden du er så snill, kan du hente drikke til de andre spillerne når de trenger det",
"Send en forespørsel om å møtes til den forrige matchen du fikk",
"Vis frem din mest kreative stilling",
"Hold en takketale på 30 sekunder",
"Drikk anstall slurker som tilsvarer",
"Ta på deg et hodeplagg for resten av spillet",
"Bytt overdel med personen til høyre for deg",
"Skyld tenna med rødvin",
"Avtal et møte",
"Personen ved siden av deg skal sende melding til crushet ditt",
"Post et bilde/story fra vorset",
"Ta håndbak med personen som ga deg boksen, taperen chugger",
"Ta av deg overdelen",
"Vis sjekketrikset på nærmeste motsatte kjønn",
"Ta deg et glass med vann",
"Chug",
"Bli enige om hvem denne personen skal sitte ved siden av",
"Syng første vers av ja vi elsker",
"Repeter navnet på alle i rommet, drikk for hver person du ikke klarer",
"Chug",
"Alle skal nå i 1 minutt stille deg spørsmål på tur, du må svare ærlig. Gjett når det har gått 1 min. 1 slurk for hvert sekund du bommer med.",
"Fortell om forrige gang.",
"Sett deg på den minste stolen tilgjengelig",
"Kyss den personen som kastet til deg",
"Hold hender med den personen som kastet den til deg i 5 minutter",
"Del en funfact om deg selv som ingen vet",
"Velg to personer i rommet du kunne hatt trekant med",
"Hva er maks antall tidligere partnere kjæresten din kunne hatt?",
"Kjør 30 sekunder free style rap eller chug",
"Vis frem det siste du søkte på",
"Bytt personlighet med den som kastet til deg resten av spillet",
"Ærlig, kommer du til å prøve deg på noen her i kveld?",
"Du er en snack! Si 3 positive ting om deg selv",
"Om du kunne velge mellom en FF som var stygg med syk i sengen, eller en som var veldig pen men forferdelig i sengen. Hvem velger du og hvorfor?",
"Dere viste hva som kom. Vis frem noen syke dansemoves!",
"Hva er det korteste du har vært på en uteplass før du har dratt hjem med noen?",
"Hvor lenge har denne tørkeperioden vart?",
"Hjelp en venn i tørke, gi ditt beste tipps for å sjarmere det motsatte kjønn",
"Kast den videre til den du syns er diggest i rommet?",
"Fyll munnen med vann. Resten av gruppa har 30 sekunder på å få deg til å le. Vinner du drikker resten 5, ellers drikker du 5.",
"Åpne et vindu å ul som en ulv i 10 sekunder!",
"Ring en 7-Eleven og spør om de har åpent",
"Ta deg en lukterunde, den som lukter best kan dele ut 5 slurker",
"Vipps et helt tilfeldig nummer 20kr",
"Få en tusj/penn tattovering på valgfritt sted av personen til høyre for deg.",
"Gå innom kamerarullen din og vis bilde nr 3.",
"Gi en dårlig striptease til personen til høyre for deg",
"Drikk fra det minste glasset tilgjengelig",
"Spis et hvitløksfedd",
"Sitt på knær de 10 neste spørsmålene",
"Still deg i vinduet, i 30 sekunder skal du rope 'Hallo!' til de som går forbi og vinke",
"Alt du sier de neste 10 spørsmålene må synges til melodien av 'Happy birthday'",
"La personen til høyre for deg ta et bilde og legg det ut på story. Du må vente 5 minutter før du kan slette det",
"Legg deg ned på gulvet å lat som du er et stykke bacon som blir stekt i 20 sekunder",
"Finn en valgfri deltaker å pjuske på de neste 10 spørsmålene",
"De andre deltakerne velger en dialekt du skal snakke resten av spillet",
"Sitt i undertøy i 10 spørsmål eller chug",
"Beskriv personen to til høyre for deg form av et improvisert dikt",
"Rop ut den første setningen du tenker på, for å så utføre den.",
"Promoter personen som kastet til deg og prøv å selg han/hun til personen til venstre for deg",
"Si ordet 'banan' etter hver setning til du får boksen igjen",
"Kyss personen som ga deg boksen de 3 beste stedene å bli kysset på - eller chug resten av drikken din",
"Gi din ærlige mening om personen som kastet boksen til deg",
"Hva er det rareste du har gjort fremfor et speil?",
"Om du kunne gjort hva som helst med personen som kastet boksne til deg. Hva ville det vært?",
"Hvilken seksuell aktivitet syns du er helt uaktuelt å gjøre?",
"Stå på henda eller hodet så lenge du klarer!",
"Send en melding/snap til 3 stykker du er interessert i og spør hvor de skal ikveld, annonser svarene.",
"Fri til personen til høyre for deg og ha en kjapp sermoni, personen til venstre skal stille som prest",
"Ta en bodyshot av magen til personen til venstre for deg",
"Sett deg i skammekroken de neste 4 spørsmålene. Ingen liker en player!",
"Hadde du angret?",
"Finn frem en frukt/grønnsak og demonstrer dine beste moves",
"Finn frem en frukt/grønnsak og demonstrer hvordan man faktisk skal gjøre det",
"Gi den beste Paradise introen (parodien) av deg selv som du kan",
"Velg en person som skal 1 vs 1 deg i chugging",
"Hvisk noe dirty inn i øret til personen til venstre. Om personen innrømmer å bli litt tent, del ut 3 slurker.",
"Dra pikk eller pung på deltakeren til høyre for deg.",
  "Personen kan leke kongen befaler de neste 5 spørsmålene",
  "Ta på leppestift",
  "Hvis du banner må du chugge",
  "Send melding til mamma å si at du har fått deg kjæreste",
  "Send melding til valgfri person og del nyheten om at du har blitt gravid!",
  "Ta over DJ-rollen ut spillet",
  "Drikk bunnslammet av nærmeste boks",
  "La en valgfri person gi deg en liten hårstuss",
  "Bytt klær",
  "De andre i rommet skal lage en drink til deg",
  "Ha rørleggersprekk resten av spillet",
  "På meg ytterjakke!",
  "Lag en improvisorisk gips av dopapir",
  "Farg en bit av håret ditt med det du har tilgjengelig (f.eks tusj eller konditorfarge)",
  "Shave hakk i øyenbrynet",
  "Teip fast en øl til begge hender",
  "Dans en Waltz med personen til venstre for deg, resten gir poeng fra 1-10",
  "Ha en sit-ups konkurranse!",
  "Ha stand-up og få folk itl å le. Klarer du dette må alle de andre drikke.",
  "Del det siste innlegget til Greta Thunberg på Facebook",
  "Gratuler en Facebookvenn med dagen!",
  "Ta hull i øret!",
  "Gi deg selv et nytt navn som alle skal bruke resten av spillet!",
  "Du er en regelbryter! Finn på en regel de andre må følge resten av spillet!",



],


};




